# Generated by Django 4.2.5 on 2024-01-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debaterequest',
            name='request_status',
            field=models.CharField(choices=[('waiting', 'انتظار'), ('accepted', 'موافق'), ('rejected', 'مرفوض')], default='waiting', max_length=200),
        ),
    ]
