# Generated by Django 4.2.5 on 2024-01-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_debaterequest_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=200)),
                ('image', models.ImageField(upload_to='')),
                ('sepcification1', models.CharField(max_length=255)),
                ('sepcification2', models.CharField(max_length=255)),
                ('sepcification3', models.CharField(max_length=255)),
                ('sepcification4', models.CharField(max_length=255)),
                ('sepcification5', models.CharField(max_length=255)),
            ],
        ),
    ]
