# Generated by Django 4.2.5 on 2024-01-14 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_servicerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerate',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 14, 17, 17, 2, 261722, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
