# Generated by Django 4.2.5 on 2024-01-19 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0019_remove_comment_father_remove_comment_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0005_servicerate_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debate', 'لوح نقاش خاص بمناظرة'), ('quote', 'لوح نقاش خاص باقتباس')], max_length=255)),
                ('status', models.CharField(choices=[('open', 'متاح'), ('closed', 'غير متاح')], max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(blank=True, to='general.comment')),
                ('debate_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.debate')),
                ('quote_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.quote')),
            ],
        ),
        migrations.CreateModel(
            name='CommentShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('X', 'X'), ('linkedin', 'Linkedin'), ('threads', 'Threads')], max_length=255)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_from_account', to=settings.AUTH_USER_MODEL)),
                ('related_to_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, to='general.commentlikes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='comment_external_shares', to='general.commentshares'),
        ),
    ]
