# Generated by Django 4.2.5 on 2023-12-28 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('token_amount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contract_ownership', models.BooleanField(default=False)),
                ('contract_controlled', models.BooleanField(default=False)),
                ('pay_for_all_tokens', models.BooleanField(default=False)),
                ('similarity_percentage', models.IntegerField(default=0)),
                ('po_neg_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VotingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=20)),
                ('used', models.BooleanField(default=False)),
                ('entity', models.CharField(choices=[('paid', 'Paid'), ('invited', 'Invited')], max_length=255)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, limit_choices_to={'entity': 'invited'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to='account.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('invoice_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
