# Generated by Django 4.2.5 on 2024-01-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_alter_debate_status'),
        ('vote', '0003_alter_votingtoken_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingtoken',
            name='debate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='debate.debate'),
            preserve_default=False,
        ),
    ]
