# Generated by Django 4.2.5 on 2024-01-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('vote', '0004_votingtoken_debate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateVotingTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('waiting', 'انتظار'), ('accepted', 'موافق'), ('rejected', 'مرفوض')], max_length=255)),
                ('debate_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.debaterequest')),
            ],
        ),
    ]
