# Generated by Django 4.2.5 on 2024-01-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('vote', '0005_debatevotingtokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DebateVotingTokens',
            new_name='DebateVotingTokensRequest',
        ),
    ]
