# Generated by Django 4.2.5 on 2024-01-11 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0006_rename_debatevotingtokens_debatevotingtokensrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingtoken',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
