# Generated by Django 4.2.5 on 2024-01-12 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_alter_debate_donation_entity_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0007_alter_votingtoken_father'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_status', models.CharField(choices=[('on-hold', 'معلق'), ('available', 'متاح'), ('not-available', 'غير متاح')], max_length=255)),
                ('box_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.debate')),
                ('debate_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.goal')),
                ('opposing_team_tokens', models.ManyToManyField(related_name='opposing_team_tokens', to='vote.votingtoken')),
                ('support_team_tokens', models.ManyToManyField(related_name='support_team_tokens', to='vote.votingtoken')),
            ],
        ),
    ]
