# Generated by Django 4.2.5 on 2024-01-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_alter_debate_donation_entity_data_and_more'),
        ('vote', '0009_alter_votebox_opposing_team_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votebox',
            name='best_quotes',
            field=models.ManyToManyField(blank=True, null=True, to='debate.quote'),
        ),
    ]
