# Generated by Django 4.2.5 on 2023-12-29 21:42

import debate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='end_time',
            field=models.DateTimeField(blank=True, default=debate.models.default_start_time, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='start_time',
            field=models.DateTimeField(blank=True, default=debate.models.default_start_time, null=True),
        ),
    ]
