# Generated by Django 4.2.5 on 2023-12-29 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('debate', '0002_alter_timeline_end_time_alter_timeline_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='debate_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.debaterequest'),
        ),
    ]
