# Generated by Django 4.2.5 on 2024-01-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_debate_debate_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('waiting', 'انتظار'), ('active', 'فعال'), ('finished', 'انتهت'), ('rejected', 'مرفوض')], default='waiting', max_length=100),
        ),
    ]
