# Generated by Django 4.2.5 on 2024-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_alter_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='status',
            field=models.CharField(choices=[('waiting', 'قيد انتظار'), ('active', 'نشطه'), ('finished', 'انتهت'), ('canceled', 'تم الالغاء'), ('archieved', 'ارشيف')], default='waiting', max_length=100),
        ),
    ]
