# Generated by Django 4.2.5 on 2024-01-11 16:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('debate', '0007_debate_donation_entity_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='donation_entity_data',
            field=taggit.managers.TaggableManager(blank=True, help_text='Name, Details, Website | Seprated using comma', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
