# Generated by Django 4.2.5 on 2024-01-11 16:54

import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('debate', '0008_alter_debate_donation_entity_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='donation_entity_data',
            field=taggit.managers.TaggableManager(blank=True, help_text='Name, Details, Website | Seprated using comma', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Debate settings: Donation Entity Data'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='donation_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Debate settings: Donation Percentage'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='winning_team_percentage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Debate settings: Winning Team Percentage'),
        ),
    ]
