# Generated by Django 4.2.5 on 2024-01-15 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_alter_debate_donation_entity_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thread_debate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.debate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('normal', 'لوح نقاش'), ('super_comment', 'لوح نقاش عام'), ('sub_comment', 'تعليق داخل لوح نقاش')], default='normal', max_length=255),
        ),
    ]
