# Generated by Django 4.2.5 on 2024-01-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0012_alter_comment_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('normal', 'لوح نقاش لتعليق'), ('super_comment', 'لوح نقاش لمناقشة'), ('sub_comment', 'تعليق داخل لوح نقاش')], default='sub_comment', max_length=255),
        ),
    ]
