# Generated by Django 4.2.5 on 2024-01-19 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0014_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='arrange',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
