# Generated by Django 4.2.5 on 2024-01-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0015_goal_arrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debate', 'لوح نقاش خاص بمناظرة'), ('quote', 'لوح نقاش خاص باقتباس')], max_length=255)),
                ('status', models.CharField(choices=[('open', 'متاح'), ('closed', 'غير متاح')], max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(blank=True, to='debate.comment')),
                ('debate_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.debate')),
                ('quote_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.quote')),
            ],
        ),
    ]
