# Generated by Django 4.2.5 on 2024-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0016_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='external_shares',
            new_name='shares',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thread_debate',
        ),
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
