# Generated by Django 4.2.5 on 2024-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0017_rename_external_shares_comment_shares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
