# Generated by Django 4.2.5 on 2024-01-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0018_alter_comment_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='father',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='commentlikes',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='commentlikes',
            name='related_to_comment',
        ),
        migrations.RemoveField(
            model_name='commentshares',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentshares',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='debate_service',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='quote_service',
        ),
    ]
