# Generated by Django 4.2.5 on 2024-01-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_comment_thread_commentshares_commentlikes_and_more'),
        ('debate', '0019_remove_comment_father_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='comments',
            field=models.ManyToManyField(blank=True, to='general.comment'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
        migrations.DeleteModel(
            name='CommentShares',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
