# Generated by Django 4.2.5 on 2023-12-29 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_alter_timeline_end_time_alter_timeline_start_time'),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatemember',
            name='birth_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='academic_backgrounds',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewer_academic_backgrounds', to='account.academicbackground'),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='academic_interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewer_academic_interests', to='account.academicinterest'),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='birth_date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='related_debates',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewer_related_debates', to='debate.debate'),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='related_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer_related_quote', to='debate.quote'),
        ),
    ]
