# Generated by Django 4.2.5 on 2023-12-29 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_debate_debate_request'),
        ('account', '0003_alter_debatemember_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatemember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images'),
        ),
        migrations.AlterField(
            model_name='debatemember',
            name='related_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_related_quote', to='debate.quote'),
        ),
    ]
