# Generated by Django 4.2.5 on 2023-12-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_debate_debate_request'),
        ('account', '0004_alter_debatemember_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsored_debates',
            field=models.ManyToManyField(blank=True, null=True, related_name='sponsor_sponsored_debates', to='debate.debate'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
