# Generated by Django 4.2.5 on 2024-01-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_debate_debate_request'),
        ('account', '0005_alter_sponsor_description_alter_sponsor_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_association',
            field=models.CharField(choices=[('member', 'Debate Member'), ('viewer', 'Debate Viewer'), ('sponsor', 'Debate Sponsor'), ('user', 'Not Associated')], default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='academic_backgrounds',
            field=models.ManyToManyField(blank=True, related_name='viewer_academic_backgrounds', to='account.academicbackground'),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='academic_interests',
            field=models.ManyToManyField(blank=True, related_name='viewer_academic_interests', to='account.academicinterest'),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='related_debates',
            field=models.ManyToManyField(blank=True, related_name='viewer_related_debates', to='debate.debate'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsored_debates',
            field=models.ManyToManyField(blank=True, related_name='sponsor_sponsored_debates', to='debate.debate'),
        ),
    ]
