# Generated by Django 4.2.5 on 2024-01-09 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_current_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicbackground',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 1, 19, 49, 868095, tzinfo=datetime.timezone.utc)),
        ),
    ]
