# Generated by Django 4.2.5 on 2024-01-09 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_academicbackground_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicinterest',
            name='user',
        ),
        migrations.AddField(
            model_name='academicinterest',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 16, 41, 3, 373835, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='academicinterest',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/debates_image'),
        ),
        migrations.AddField(
            model_name='academicinterest',
            name='url',
            field=models.URLField(default='https://quotefather.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicbackground',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 9, 16, 41, 3, 374652, tzinfo=datetime.timezone.utc)),
        ),
    ]
