# Generated by Django 4.2.5 on 2024-01-10 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_academicinterest_user_academicinterest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 9, 52, 29, 471188, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='academicinterest',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 9, 52, 29, 470246, tzinfo=datetime.timezone.utc)),
        ),
    ]
