# Generated by Django 4.2.5 on 2024-01-10 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_academicbackground_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 17, 6, 14, 137355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='academicinterest',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 17, 6, 14, 136918, tzinfo=datetime.timezone.utc)),
        ),
    ]
