# Generated by Django 4.2.5 on 2024-01-15 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_alter_academicbackground_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 7, 21, 18, 263030, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='academicinterest',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 7, 21, 18, 262554, tzinfo=datetime.timezone.utc)),
        ),
    ]
