# Generated by Django 4.2.5 on 2024-01-16 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_academicbackground_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 17, 50, 10, 970041, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='academicinterest',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 17, 50, 10, 969462, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='debateviewer',
            name='profile_image',
            field=models.ImageField(default='/media/profile_images/default/1.png', upload_to='media/profile_images'),
        ),
    ]
