# Generated by Django 4.2.5 on 2024-01-19 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_academicbackground_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 19, 17, 45, 37, 66987, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='academicinterest',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 19, 17, 45, 37, 66355, tzinfo=datetime.timezone.utc)),
        ),
    ]
